{
  inputs,
  lib,
  config,
  pkgs,
  ...
}: {
  hardware.fancontrol = {
    enable = true;
    config = ''
    # Configuration file generated by pwmconfig, changes will be lost
    INTERVAL=10
    DEVPATH=hwmon2=devices/platform/nct6775.656 hwmon3=devices/pci0000:00/0000:00:18.3 hwmon7=devices/pci0000:00/0000:00:01.1/0000:01:00.0/0000:02:00.0/0000:03:00.0
    DEVNAME=hwmon2=nct6799 hwmon3=k10temp hwmon7=amdgpu
    FCTEMPS=hwmon2/pwm4=hwmon7/temp3_input hwmon2/pwm2=hwmon7/temp3_input hwmon2/pwm1=hwmon3/temp1_input
    FCFANS=hwmon2/pwm4=hwmon2/fan4_input hwmon2/pwm2=hwmon2/fan2_input hwmon2/pwm1=hwmon2/fan1_input
    MINTEMP=hwmon2/pwm4=30 hwmon2/pwm2=30 hwmon2/pwm1=30
    MAXTEMP=hwmon2/pwm4=85 hwmon2/pwm2=85 hwmon2/pwm1=80
    MINSTART=hwmon2/pwm4=20 hwmon2/pwm2=40 hwmon2/pwm1=20
    MINSTOP=hwmon2/pwm4=10 hwmon2/pwm2=20 hwmon2/pwm1=10
    MAXPWM=hwmon2/pwm4=90 hwmon2/pwm2=180 hwmon2/pwm1=150
    '';
  };
}
